image&nbsp;&nbsp;&nbsp;	name&nbsp;	pass&nbsp;&nbsp;&nbsp;	fail&nbsp;&nbsp;&nbsp;	errors&nbsp;&nbsp;&nbsp;	skipped&nbsp;&nbsp;&nbsp;	avg time&nbsp;	fail msg&nbsp;
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testTimeRangeTrackerNullIsSameAsTimeRangeNull	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testTimeRangeInitialized	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testLegacySerialization	201	0	 0	0	.05	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testMetricsSourceBaseSourcePassthrough	98	0	 2	0	6.08	Failed after attempts=15, exceptions:<br/>2020-02-03T21:45:01.613Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.718Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.927Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.238Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.748Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:04.058Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:06.079Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:10.119Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:20.216Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:30.312Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:40.380Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:50.422Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:10.495Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:30.510Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:50.713Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=15, exceptions:<br/>2020-02-03T21:45:01.613Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.718Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.927Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.238Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.748Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:04.058Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:06.079Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:10.119Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:20.216Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:30.312Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:40.380Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:50.422Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:10.495Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:30.510Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:50.713Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AdminOverAsyncAdmin.rollWALWriter(AdminOverAsyncAdmin.java:574)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.setup(TestReplicationEndpoint.java:106)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncAdminRequestRetryingCaller.lambda$doCall$4(AsyncAdminRequestRetryingCaller.java:68)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$2.run(RawAsyncHBaseAdmin.java:431)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:378)<br/>&nbsp; &nbsp;... 34 more<br/>Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>Caused by: java.net.ConnectException: Connection refused<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testReplicationEndpointReturnsFalseOnReplicate	100	0	 0	0	4.87	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testWALEntryFilterAddValidation	100	0	 0	0	2.68	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testSimpleInRange	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testSerialization	201	0	 0	0	.12	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testConcurrentIncludeTimestampCorrectness	201	0	 0	0	8.53	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testRangeConstruction	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestStripeStoreEngine#testCreateBasedOnConfig	100	0	 0	0	2.18	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testInterClusterReplication	65	33	 2	0	25.32	Waiting timed out after [30,000] msec Failed to replicate all edits, expected = 2500 replicated = 2499<br/><br/>java.lang.AssertionError: Waiting timed out after [30,000] msec Failed to replicate all edits, expected = 2500 replicated = 2499<br/>&nbsp; &nbsp;at org.junit.Assert.fail(Assert.java:89)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.Waiter.waitFor(Waiter.java:203)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.Waiter.waitFor(Waiter.java:137)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.testInterClusterReplication(TestReplicationEndpoint.java:235)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testWALEntryFilterUpdateValidation	98	0	 2	0	4.39	Failed after attempts=15, exceptions:<br/>2020-02-03T21:50:38.950Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.058Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.268Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.577Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:40.090Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:41.111Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:43.131Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:47.154Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:57.203Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:07.249Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:18.020Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:28.115Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:48.240Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:08.296Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:28.431Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=15, exceptions:<br/>2020-02-03T21:50:38.950Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.058Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.268Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.577Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:40.090Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:41.111Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:43.131Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:47.154Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:57.203Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:07.249Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:18.020Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:28.115Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:48.240Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:08.296Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:28.431Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AdminOverAsyncAdmin.rollWALWriter(AdminOverAsyncAdmin.java:574)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.setup(TestReplicationEndpoint.java:106)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncAdminRequestRetryingCaller.lambda$doCall$4(AsyncAdminRequestRetryingCaller.java:68)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$2.run(RawAsyncHBaseAdmin.java:431)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:378)<br/>&nbsp; &nbsp;... 34 more<br/>Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>Caused by: java.net.ConnectException: Connection refused<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestStripeStoreEngine#testCompactionContextForceSelect	100	0	 0	0	.46	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testWALEntryFilterFromReplicationEndpoint	98	0	 2	0	8.00	Failed after attempts=15, exceptions:<br/>2020-02-03T21:48:46.631Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.738Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.948Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.257Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.768Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:48.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:50.800Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:54.812Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:04.910Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:16.545Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:26.583Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:36.663Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:56.720Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:16.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:36.921Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=15, exceptions:<br/>2020-02-03T21:48:46.631Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.738Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.948Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.257Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.768Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:48.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:50.800Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:54.812Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:04.910Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:16.545Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:26.583Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:36.663Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:56.720Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:16.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:36.921Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AdminOverAsyncAdmin.rollWALWriter(AdminOverAsyncAdmin.java:574)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.setup(TestReplicationEndpoint.java:106)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncAdminRequestRetryingCaller.lambda$doCall$4(AsyncAdminRequestRetryingCaller.java:68)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$2.run(RawAsyncHBaseAdmin.java:431)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:378)<br/>&nbsp; &nbsp;... 34 more<br/>Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>Caused by: java.net.ConnectException: Connection refused<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios#testRegionReplicasCreated	100	0	 0	0	12.45	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testAlwaysDecrementingSetsMaximum	201	0	 0	0	.05	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios#testWhenRestart	99	1	 0	0	11.12	expected:<61> but was:<59><br/><br/>java.lang.AssertionError: expected:<61> but was:<59><br/>&nbsp; &nbsp;at org.junit.Assert.fail(Assert.java:89)<br/>&nbsp; &nbsp;at org.junit.Assert.failNotEquals(Assert.java:835)<br/>&nbsp; &nbsp;at org.junit.Assert.assertEquals(Assert.java:647)<br/>&nbsp; &nbsp;at org.junit.Assert.assertEquals(Assert.java:633)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios.assertReplicaDistributed(TestRegionReplicasWithRestartScenarios.java:159)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios.testWhenRestart(TestRegionReplicasWithRestartScenarios.java:140)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testArriveAtRightAnswer	201	0	 0	0	.14	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testExtreme	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testCustomReplicationEndpoint	100	0	 0	0	6.57	
